# Site settings
slogan: Affordable Organic Nutrients
title: Bali Compost Crafters - Affordable Organic Nutrients
email: info@balicompostcrafters.com
description: "Bali Compost Crafters, purveyors of the finest quality affordable organic nutrients"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
# Footer settings
footer: Bali Compost Crafters
sass:
  style: compressed
  sass_dir: _sass
social:
  - title: facebook
    url: https://www.facebook.com/BaliCompostCrafters
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "posts" # previously `post` in Jekyll 2.2.
        values:
            layout: "default"
