- title: Rainforest Compost
  display_title: COMPOST
  id: rainforest_compost
  colour: '#422D19'
  description: |
      This stuff is really good compost, it's epic! It makes all plants grow better.
      You can get a really good feel for it with your hands!
  benefits:
    - Enhances crop yields.
    - Perfect for pot plants.
    - Retains water.
    - Rejuvenates farmland.
    - Promotes healthy crops.

- title: Topsoil
  display_title: TOPSOIL
  id: topsoil
  colour: '#E05733'
  description: |
      Really, really good topsoil, it makes the top of your garden look and feel great!
  benefits:
    - Great for lawns and gardens
    - Perfect for raised bed gardens
    - Retains water
    - Replace eroded soil
    - Complements our compost

- title: Mulch
  display_title: MULCH
  id: mulch
  colour: '#399495'
  description: |
      Mulch, which is really good quality and allows people to protect their top-soil from the rain.
  benefits:
    - Protects soil and plants.
    - Encourages water retention.
    - Retards weed growth.
    - Aerates soil.
    - Complements top soil.
